# Type stub for the mylib package's public surface.
#
# The compiled extension's stub (mylib_ext.pyi) is generated by nanobind at build
# time; this file declares the package re-exports plus __version__ (which stubgen
# skips because it is a dunder).
from .mylib_ext import sum as sum

__version__: str

__all__ = ["__version__", "sum"]
