/// @file sum.hpp
/// @brief Addition primitives for the mylib library.
#pragma once

#include <mylib/mylib_export.h> // generated by CMake (generate_export_header)

#include <concepts>

/// @namespace mylib
/// @brief Public namespace for all mylib symbols.
namespace mylib {

/// @brief A type that can participate in arithmetic addition.
///
/// Constrains the sum() template to the built-in integral and floating-point
/// types, giving callers a clear compile-time error instead of a deep template
/// instantiation failure.
template <typename T>
concept Number = std::integral<T> || std::floating_point<T>;

/// @brief Returns the sum of two numbers.
///
/// This is a `constexpr` template usable in constant expressions. It is
/// `noexcept` because built-in arithmetic never throws.
///
/// @tparam T an arithmetic type satisfying @ref Number
/// @param a the left addend
/// @param b the right addend
/// @returns `a + b`
///
/// @code
/// static_assert(mylib::sum(2, 3) == 5);
/// @endcode
template <Number T> [[nodiscard]] constexpr T sum(T a, T b) noexcept
{
    return a + b;
}

/// @brief Adds two 64-bit integers (non-template, defined in @c sum.cpp).
///
/// Provided so the library ships a real compiled translation unit that is
/// installed, exported, and versioned — exercising the full packaging machinery.
///
/// @param a the left addend
/// @param b the right addend
/// @returns `a + b`
[[nodiscard]] MYLIB_EXPORT long long sum(long long a, long long b) noexcept;

} // namespace mylib
